dist: xenial
sudo: required
language: python

before_install:
  - sudo apt-get install python3-pip
  - pip3 install markdown\<3.0.0 pygments

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH

script:
  - git clone https://github.com/${TRAVIS_REPO_SLUG}.git sources --depth 1 -b sources
  - git clone https://github.com/${TRAVIS_REPO_SLUG}.git generator --depth 1 -b generator
  - cp -a generator/webroot workdir && cp -a sources/{post,content.php,index.md} generator/{mdgen.py,sitegen.php} workdir
  - cd workdir && mv img/favicon.ico . && php sitegen.php && rm -r post/*.md index.md *.{py,php}
  
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: workdir
  target-branch: master
  on:
    branch: sources
